Change the style
Listenbourg/Traduction pull request #1
Opened 2022-11-09 22:20 UTC by NonozgYtb

Applying the layout "Outil 1", according to the figma page

2022-11-09 23:22 UTC, thaliumFr requested changes
Faut apprendre les variables notamment l'existence du --border-radius mais a part les petits oublies récurrent je vois pas d'absurdités totale + tu as été tarpin rapide pour faire tous ça

2022-11-09 23:22 UTC, thaliumFr commented on css/layout-outil-1.scss
> +	height: 100%;
Il conviendrait mieux d'utiliser min-height: 100vh; si on veut chipoter un peu

2022-11-09 23:22 UTC, thaliumFr commented on css/layout-outil-1.scss
> +		font-family: "HK Grotesk";
var(--font-listen) + tous le site est sensé utiliser cette font déjà donc est sensé être inutile

2022-11-09 23:22 UTC, thaliumFr commented on css/listenbourg-traduction.scss
> +		font-family: "HK Grotesk", sans-serif;
var(--font-listen) + tous le site est sensé utiliser cette font déjà donc est sensé être inutile

2022-11-09 23:22 UTC, thaliumFr commented on css/listenbourg-traduction.scss
> +		color: rgb(236, 34, 19);
Nouvelle couleur hors du design system? Peut-être rajouter une variable danse design system si c'est le cas

2022-11-09 23:22 UTC, thaliumFr commented on css/listenbourg-traduction.scss
> +	border-radius: 8px;
Il y a une variable dans le design system pour éviter d'avoir plusieurs radius différents et que si un jour on veuille changer le radius que ca le fasse partout
var(--border-radius)

2022-11-09 23:22 UTC, thaliumFr commented on css/listenbourg-traduction.scss
> +		border-bottom: 1px dashed rgb(236, 34, 19);
Nouvelle couleur hors design system -> nouvelle variable?

2022-11-09 23:22 UTC, thaliumFr commented on css/listenbourg-traduction.scss
> +		color: #ec6a13;
Nouvelle couleur hors design system -> nouvelle variable?

2022-11-09 23:22 UTC, thaliumFr commented on css/listenbourg-traduction.scss
> +		background-color: #ec6a13;
Nouvelle couleur hors design system -> nouvelle variable?
(En plus elle revient plusieurs fois)

2022-11-09 23:22 UTC, thaliumFr commented on css/listenbourg-traduction.scss
> +		background-color: rgb(236, 34, 19);
Nouvelle couleur hors design system -> nouvelle variable?
(En plus tu utilises cette couleur a plusieurs endroits)

2022-11-09 23:22 UTC, thaliumFr commented on css/layout-outil-1.scss
> +			border-radius: 0 0 8px 8px;
border-radius: 0 0 var(--border-radius) var(--border-radius);

2022-11-09 23:22 UTC, thaliumFr commented on css/layout-outil-1.scss
> +		border-radius: 8px;
var(--border-radius)

2022-11-09 23:22 UTC, thaliumFr commented on css/listenbourg-traduction.scss
> +		border-bottom: 1px dashed #ec6a13;
Nouvelle couleur hors design system -> nouvelle variable?

2022-11-09 23:45 UTC, NonozgYtb commented
Merci beaucoup @thaliumFr, c'est vrai j'ai un peu speedrun le truc vu que le figma était déjà fait, j'ai parfois juste recopier le css depuis figma même si il falait faire aussi des ajustements ! J'ai fais un commit pour les fixs !

2022-11-10 08:38 UTC, Just1bridou commented
![image](https://user-images.githubusercontent.com/45208166/201033374-0c1732e9-5ba0-43bb-aaa2-17cfdfc71a5a.png)

Tout est okay dans l'ensemble juste deux trucs :

- Je trouve que les textes "Français" et "Listenbourgeois" sont un peu trop gros, je pense que c'est la même font size que "Texte source" et  "Traduction" mais avec la border ça donne l'impression d'être un peu trop gros
- Les boutons "Listenbourg.org" et "Acceuil" en haut à droite ne sont pas très compréhensibles (listenbourg.org ressemble plus à du texte qu'a un lien cliquable / bouton), je verrai plus un bouton de ce style (icon + texte) pour aller sur le site listenbourg.org
![image](https://user-images.githubusercontent.com/45208166/201040708-80a812d7-c6c0-4c7c-a8cb-d907a2a0704c.png)
et le bouton retour à l'accueil ne sert à rien, le retour à l'accueil se fait généralement en cliquant sur le logo en haut à gauche

2022-11-10 23:29 UTC, NonozgYtb commented
Ce sera fait un peu plus tard !

2022-11-10 23:29 UTC, merged